# Generated by Django 5.0.6 on 2024-06-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_merge_20190815_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
    ]
