# Generated by Django 5.0.6 on 2024-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_remove_perfil_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('R', 'Locatário'), ('E', 'Locador')], default='E', max_length=2),
        ),
    ]
