# Generated by Django 5.0.6 on 2024-06-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190815_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={},
        ),
    ]
