# Generated by Django 5.0.6 on 2024-06-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_variacao_options_alter_produto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing_promocional',
        ),
        migrations.AddField(
            model_name='variacao',
            name='quantidade_dias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('A', 'ALUGUEL')], default='A', max_length=1),
        ),
    ]
