# Generated by Django 5.0.6 on 2024-06-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_rename_quantidade_dias_variacao_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='name',
            new_name='nome',
        ),
    ]
