# Generated by Django 5.0.6 on 2024-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_rename_name_variacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='quantidade_dias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
