# Generated by Django 5.0.6 on 2024-06-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_variacao_quantidade_dias_alter_variacao_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='quantidade_dias',
            new_name='quandidade_dias',
        ),
    ]
