# Generated by Django 5.0.6 on 2024-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0020_alter_variacao_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='quandidade_dias',
        ),
        migrations.AlterField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
