# Generated by Django 5.0.6 on 2024-06-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0021_remove_variacao_quandidade_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='quandidade_dias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
