# Generated by Django 5.0.6 on 2024-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_data_cadastro_pedido_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel'), ('A', 'ALUGADO')], default='A', max_length=1),
        ),
    ]
