# Generated by Django 5.0.6 on 2024-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel'), ('A', 'ALUGADO')], default='D', max_length=1),
        ),
    ]
