# Generated by Django 5.0.6 on 2024-06-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='emprestado',
            new_name='alugado',
        ),
    ]
